# Author: Duncan Tilley
# Platform: Arch linux (with oh-my-zsh)

# Some oh-my-zsh settings
export ZSH=/home/duncan/.oh-my-zsh
ZSH_THEME="bira-custom"
DEFAULT_USER="duncan"

# Load the git plugin and start oh-my-zsh
plugins=(git)
source $ZSH/oh-my-zsh.sh

# Some useful aliases
alias sudo='sudo '
alias g++='g++ -std=c++11'
alias pacinstall='pacman -S'
alias pacremove='pacman -Rns'
alias update='pacman -Sy'
alias upgrade='pacman -Syu'

