set backspace=indent,eol,start
set shiftwidth=4
" tab width in spaces
set tabstop=4
" autoindent next line
set autoindent
" show line numbers
set number
" highlight current line
set cursorline
" autocomplete command menu
set wildmenu
" redraw the screen only when necessary
set lazyredraw
" search as characters are entered
set incsearch
" highlight search matches
set hlsearch
" show the status line
set laststatus=2
set statusline=%f%m%r%h%w
" reduce the updatetime to 250ms
set updatetime=250

colorscheme custom
syntax on

" switch assembly syntax to use nasm syntax
" instead of AT&T syntax
au BufRead,BufNewFile *.asm set filetype=nasm

" keymaps
" faster left-right movement
noremap <C-h> b
noremap <C-l> w
noremap H 0
noremap L $
" faster up-down movement
noremap J }
noremap K {
" move line up or down
noremap <C-j> :m .+1<CR>
noremap <C-k> :m .-2<CR>
inoremap <C-j> <Esc>:m .+1<CR>i
inoremap <C-k> <Esc>:m .-2<CR>i
" classic undo/redo
noremap <C-z> u
noremap <C-y> <C-r>
" remove annoying exits
inoremap <C-p> <Esc>
inoremap <C-[> <Esc>
" insert mode movement
inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>
" window mappings
execute "set <M-h>=h"
execute "set <M-j>=j"
execute "set <M-k>=k"
execute "set <M-l>=l"
noremap <M-h> <C-w>h
noremap <M-j> <C-w>j
noremap <M-k> <C-w>k
noremap <M-l> <C-w>l
noremap <C-v> :vsplit<CR>
noremap <C-h> :split<CR>

