#!/bin/bash

# bspwm autostart
# author: tilleyd

# keybindings
sxhkd &

# set up multiple monitors
if xrandr | grep "HDMI-1 connected" > /dev/null;
then
    xrandr --output HDMI-1 --auto --primary --right-of eDP-1
fi

# disable screen blanking
xset dpms 0 0 0 && xset -dpms && xset s noblank && xset s off

# set the touchpad to the correct state
#touchpad-update

#
# startup applications
#

numlockx &
setxkbmap -option caps:escape &
nitrogen --restore &
picom &
polybar default &
#nm-applet &
blueman-applet &
