#!/bin/bash

# bspwm autostart
# author: tilleyd

# keybindings
sxhkd &

# set up multiple monitors
if xrandr | grep "HDMI-1 connected" > /dev/null;
then
    xrandr --output HDMI-1 --auto --primary --right-of eDP-1
fi

# disable screen blanking
xset dpms 0 0 0 && xset -dpms && xset s noblank && xset s off

# set the touchpad to the correct state
#touchpad-update

# enable numlock
numlockx

#
# startup applications
#

# set the wallpaper
$HOME/.fehbg &
#nitrogen --restore &

# run compositor
picom &

# panel
polybar default &

# panel applets
#nm-applet &
blueman-applet &
