#! /bin/sh

if xrandr | grep "HDMI-1 connected" > /dev/null;
then
    # put only the first desktop on the laptop monitor
    bspc monitor eDP-1 -d 1
    bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

# Desktop
bspc config window_gap           24
bspc config split_ratio          0.5
# let all windows become fullscreen in monocle
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# polybar will handle margins per monitor
# bspc config top_padding          0

bspc config presel_feedback_color "#abb2bf"

# Borders
bspc config border_width         2
bspc config focused_border_color "#abb2bf"
bspc config normal_border_color  "#282c34"
bspc config active_border_color  "#282c34"

# Focus
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config click_to_focus      any
bspc config swallow_first_click false

# Mouse settings
# Use alt + btn to resize/move windows
bspc config pointer_modifier    mod1
xsetroot -cursor_name left_ptr

# Rules
bspc rule -a Gun\ Game state=floating
bspc rule -a Nitrogen state=floating follow=on center=true rectangle=960x640+0+0
bspc rule -a SpeedCrunch state=floating follow=on center=true rectangle=960x640+0+0
bspc rule -a Zathura state=tiled follow=on
bspc rule -a scratch state=floating follow=on center=true rectangle=960x640+0+0
bspc rule -a matplotlib state=floating follow=on center=true rectangle=960x640+0+0

$HOME/.config/bspwm/autostart &

wait
