#! /bin/sh

if xrandr | grep "HDMI-1 connected" > /dev/null;
then
    # put only the first desktop on the laptop monitor
    bspc monitor eDP-1 -d 1
    bspc monitor HDMI-1 -d 2 3 4 5 6 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width         1
bspc config window_gap           16
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# polybar will handle margins per monitor
# bspc config top_padding          0

bspc config presel_feedback_color "#8fa1b3"
bspc config focused_border_color "#8fa1b3"

$HOME/.config/bspwm/autostart &

wait
