# zsh config
# author: tilleyd

export ZSH=/usr/share/oh-my-zsh
ZSH_THEME="dtys"
DEFAULT_USER="tilleyd"

# plugins list
plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

# some useful aliases
alias vim='nvim'
alias ls='ls --color=auto --group-directories-first'
alias sudo='sudo '
alias objdump='objdump -M intel'
alias su='su -p'

# environment variables
export EDITOR="/usr/bin/nvim"
export XDG_CONFIG_HOME="$HOME/.config"

# ssh
eval $(keychain --eval --quiet)

# print the date
#echo `date +"Started at %F %H:%M"` in `pwd`
